# Generated by Django 4.0.4 on 2022-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_texteditor_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texteditor',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
